name: PyInstaller Windows Release

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use PyInstaller to freeze the program
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./
          requirements: ./requirements.txt
          spec: LevelSync.spec

      # Zip up the exe with the config and readme
      - uses: papeloto/action-zip@v1
        with:
          files: dist/windows/LevelSync.exe config.ini README.md
          dest: LevelSync.zip

      - uses: actions/upload-artifact@v2
        with:
          name: LevelSync.zip
          path: ./LevelSync.zip

